site_name: Polytoria Scripting API
copyright: Copyright &copy; 2019 - 2024 Polytoria
theme:
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.annotate
  name: material
  logo: assets/logo.svg
  font:
    text: Poppins
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - tables
extra_css:
  - assets/extra.css
